name = "Swing Ax"
description = "A wild swing with a rusty ax."
action_text = "{{character}} swings ax at {{target}}"
engagement_types = ["battle"]
costs = []
role = "attack"
targets = ["opponent"]

[[effects]]
name = "ax_damage"
trigger_info = { type = "once" }
effect_type = { type = "attribute_update", attribute_id = "hp", value = -15 }
description = { text = "Axe chops for {{abs_value}}" }
