[[inventories]]
id = "inventory"
bag_size = 100

[[inventories.equipment_slots]]
name = "left_hand"
item_types = ["weapon", "shield"]

[[inventories.equipment_slots]]
name = "right_hand"
item_types = ["weapon", "shield"]

[[inventories.equipment_slots]]
name = "body"
item_types = ["body_armor"]

[[inventories.equipment_slots]]
name = "head"
item_types = ["head_armor"]

[[inventories.equipment_slots]]
name = "feet"
item_types = ["shoes"]

[[inventories.equipment_slots]]
name = "amulet_1"
item_types = ["amulet"]

[[inventories.equipment_slots]]
name = "amulet_2"
item_types = ["amulet"]

[[inventories.equipment_slots]]
name = "amulet_3"
item_types = ["amulet"]

[[inventories.equipment_slots]]
name = "amulet_4"
item_types = ["amulet"]
