name = "Cyborg"
description = "A cybernetically enhanced fighter with integrated energy weapons."

[[attributes]]
definition_id = "hp"
min_value = 0
max_value = 90
current_value = 90

[[attributes]]
definition_id = "mp"
min_value = 0
max_value = 60
current_value = 60

innate_abilities = ["heat_beam", "electric_shot"]
