name = "Survivor"
description = "A scrappy melee brawler who clawed their way through the wasteland."

[[attributes]]
definition_id = "hp"
min_value = 0
max_value = 120
current_value = 120

[[attributes]]
definition_id = "mp"
min_value = 0
max_value = 20
current_value = 20

innate_abilities = ["basic_attack", "sawed_off_shotgun"]
